# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\OneDrive - Universidad Internacional de las Américas (UIA)\Escritorio\ProyectoFinal\ProyectoFinal\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 600)
        Login.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(14)
        Login.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\HP\\OneDrive - Universidad Internacional de las Américas (UIA)\\Escritorio\\ProyectoFinal\\ProyectoFinal\\recursos/trespatitos.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(118, 0, 176, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(240, 10, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblSaludo = QtWidgets.QLabel(self.centralwidget)
        self.lblSaludo.setGeometry(QtCore.QRect(240, 120, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblSaludo.setFont(font)
        self.lblSaludo.setObjectName("lblSaludo")
        self.lblUsuario = QtWidgets.QLabel(self.centralwidget)
        self.lblUsuario.setGeometry(QtCore.QRect(240, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setObjectName("lblUsuario")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUsuario.setGeometry(QtCore.QRect(370, 200, 113, 22))
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtContasenia = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContasenia.setGeometry(QtCore.QRect(370, 240, 113, 22))
        self.txtContasenia.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtContasenia.setObjectName("txtContasenia")
        self.btnIngresar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIngresar.setGeometry(QtCore.QRect(260, 320, 93, 28))
        self.btnIngresar.setObjectName("btnIngresar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(430, 320, 93, 28))
        self.btnCancelar.setObjectName("btnCancelar")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.lblTitulo.setText(_translate("Login", "Empresa Tres Patitos"))
        self.lblSaludo.setText(_translate("Login", "Ingrese su usuario, por favor. "))
        self.lblUsuario.setText(_translate("Login", "Usuario:"))
        self.label.setText(_translate("Login", "Contraseña:"))
        self.btnIngresar.setText(_translate("Login", "Ingresar"))
        self.btnCancelar.setText(_translate("Login", "Salir"))
