# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\OneDrive - Universidad Internacional de las Américas (UIA)\Escritorio\Proyecto-Python\ProyectoFinal\ProyectoFinal\ProyectoFinal\ProyectoFinal\mdi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mdiWindow(object):
    def setupUi(self, mdiWindow):
        mdiWindow.setObjectName("mdiWindow")
        mdiWindow.resize(817, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\HP\\OneDrive - Universidad Internacional de las Américas (UIA)\\Escritorio\\Proyecto-Python\\ProyectoFinal\\ProyectoFinal\\ProyectoFinal\\ProyectoFinal\\recursos/trespatitos.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mdiWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mdiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 801, 541))
        self.mdiArea.setMinimumSize(QtCore.QSize(500, 500))
        self.mdiArea.setSizeIncrement(QtCore.QSize(500, 500))
        self.mdiArea.setObjectName("mdiArea")
        mdiWindow.setCentralWidget(self.centralwidget)
        self.mniMenubar = QtWidgets.QMenuBar(mdiWindow)
        self.mniMenubar.setGeometry(QtCore.QRect(0, 0, 817, 26))
        self.mniMenubar.setObjectName("mniMenubar")
        self.mniUsuarios = QtWidgets.QMenu(self.mniMenubar)
        self.mniUsuarios.setObjectName("mniUsuarios")
        self.mniEmpleados = QtWidgets.QMenu(self.mniMenubar)
        self.mniEmpleados.setObjectName("mniEmpleados")
        self.mniDepartamentos = QtWidgets.QMenu(self.mniMenubar)
        self.mniDepartamentos.setObjectName("mniDepartamentos")
        self.mniBienes = QtWidgets.QMenu(self.mniMenubar)
        self.mniBienes.setObjectName("mniBienes")
        self.mniReportes = QtWidgets.QMenu(self.mniMenubar)
        self.mniReportes.setObjectName("mniReportes")
        mdiWindow.setMenuBar(self.mniMenubar)
        self.statusbar = QtWidgets.QStatusBar(mdiWindow)
        self.statusbar.setObjectName("statusbar")
        mdiWindow.setStatusBar(self.statusbar)
        self.mniUsuario = QtWidgets.QAction(mdiWindow)
        self.mniUsuario.setObjectName("mniUsuario")
        self.mniEmpleado = QtWidgets.QAction(mdiWindow)
        self.mniEmpleado.setObjectName("mniEmpleado")
        self.mniDepartamento = QtWidgets.QAction(mdiWindow)
        self.mniDepartamento.setObjectName("mniDepartamento")
        self.mniAsignacionBienes = QtWidgets.QAction(mdiWindow)
        self.mniAsignacionBienes.setObjectName("mniAsignacionBienes")
        self.mniTabla_Reportes = QtWidgets.QAction(mdiWindow)
        self.mniTabla_Reportes.setObjectName("mniTabla_Reportes")
        self.mniDesligarBienes = QtWidgets.QAction(mdiWindow)
        self.mniDesligarBienes.setObjectName("mniDesligarBienes")
        self.mniBienes_2 = QtWidgets.QAction(mdiWindow)
        self.mniBienes_2.setObjectName("mniBienes_2")
        self.mniUsuarios.addAction(self.mniUsuario)
        self.mniEmpleados.addAction(self.mniEmpleado)
        self.mniDepartamentos.addAction(self.mniDepartamento)
        self.mniBienes.addAction(self.mniAsignacionBienes)
        self.mniBienes.addAction(self.mniDesligarBienes)
        self.mniBienes.addAction(self.mniBienes_2)
        self.mniReportes.addAction(self.mniTabla_Reportes)
        self.mniMenubar.addAction(self.mniUsuarios.menuAction())
        self.mniMenubar.addAction(self.mniEmpleados.menuAction())
        self.mniMenubar.addAction(self.mniDepartamentos.menuAction())
        self.mniMenubar.addAction(self.mniBienes.menuAction())
        self.mniMenubar.addAction(self.mniReportes.menuAction())

        self.retranslateUi(mdiWindow)
        QtCore.QMetaObject.connectSlotsByName(mdiWindow)

    def retranslateUi(self, mdiWindow):
        _translate = QtCore.QCoreApplication.translate
        mdiWindow.setWindowTitle(_translate("mdiWindow", "Empresa Tres Patitos"))
        self.mniUsuarios.setTitle(_translate("mdiWindow", "Usuarios"))
        self.mniEmpleados.setTitle(_translate("mdiWindow", "Empleados"))
        self.mniDepartamentos.setTitle(_translate("mdiWindow", "Departamentos"))
        self.mniBienes.setTitle(_translate("mdiWindow", "Bienes"))
        self.mniReportes.setTitle(_translate("mdiWindow", "Reportes"))
        self.mniUsuario.setText(_translate("mdiWindow", "Usuario"))
        self.mniEmpleado.setText(_translate("mdiWindow", "Empleados"))
        self.mniDepartamento.setText(_translate("mdiWindow", "Departamentos"))
        self.mniAsignacionBienes.setText(_translate("mdiWindow", "Asignacion de Bienes"))
        self.mniTabla_Reportes.setText(_translate("mdiWindow", "Tabla Reportes"))
        self.mniDesligarBienes.setText(_translate("mdiWindow", "Desligar Bienes"))
        self.mniBienes_2.setText(_translate("mdiWindow", "Bienes"))
