# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\OneDrive - Universidad Internacional de las Américas (UIA)\Escritorio\Ultimo Intento\empleado.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Empleado(object):
    def setupUi(self, Empleado):
        Empleado.setObjectName("Empleado")
        Empleado.resize(800, 800)
        Empleado.setMinimumSize(QtCore.QSize(800, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\HP\\OneDrive - Universidad Internacional de las Américas (UIA)\\Escritorio\\Ultimo Intento\\recursos/trespatitos.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Empleado.setWindowIcon(icon)
        self.lblTitulo = QtWidgets.QLabel(Empleado)
        self.lblTitulo.setGeometry(QtCore.QRect(120, 60, 55, 16))
        self.lblTitulo.setObjectName("lblTitulo")

        self.retranslateUi(Empleado)
        QtCore.QMetaObject.connectSlotsByName(Empleado)

    def retranslateUi(self, Empleado):
        _translate = QtCore.QCoreApplication.translate
        Empleado.setWindowTitle(_translate("Empleado", "Empleado"))
        self.lblTitulo.setText(_translate("Empleado", "Empleado"))
